
AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template provisions an Amazon SageMaker Studio Domain and a user profile.

Resources:
  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      AppNetworkAccessType: PublicInternetOnly
      AuthMode: IAM
      DefaultUserSettings: 
        ExecutionRole: arn:aws:iam::930627915954:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
      DomainName: DS-RD-Team
      SubnetIds:                                                      
        - subnet-07a3c08cfc80e54f1
      VpcId: vpc-0da1729371232a3ab

  SageMakerUser:
    Type: "AWS::SageMaker::UserProfile"
    Properties:
      DomainId: !Ref SageMakerDomain
      UserProfileName: "Tochi"
      UserSettings:
        ExecutionRole: arn:aws:iam::930627915954:role/service-role/AmazonSageMaker-ExecutionRole-20240912T123624
      

      
